theme: minima
title: github-pages
author: yuler
email: joyful4yu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a programmer.
  My name is yuler.

# social links
twitter_username: joyful4yu
github_username:  yuler

show_excerpts: true # set to false to remove excerpts on the homepage
